import {
  Blocks,
  Bot,
  Braces,
  Brain,
  ClipboardCheck,
  Cpu,
  Database,
  Gauge,
  History,
  Monitor,
  Network,
  Server,
  ShieldCheck,
  Sparkles,
  TestTube2,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { IconType } from "react-icons";
import {
  SiApachejmeter,
  SiCss,
  SiDocker,
  SiGithub,
  SiGithubactions,
  SiJavascript,
  SiMysql,
  SiOpenjdk,
  SiPhp,
  SiScikitlearn,
  SiSelenium,
  SiStreamlit,
  SiSymfony,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiReact,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

import type { SkillCategoryId } from "@/types/content";

export const categoryIcons: Record<SkillCategoryId, LucideIcon> = {
  web: Monitor,
  backend: Server,
  qa: TestTube2,
  automation: Bot,
  languages: Braces,
  tools: Wrench,
  learning: Sparkles,
};

/** Icône associée à une technologie (logo officiel si disponible, pictogramme sinon). */
export const techIcons: Record<string, IconType | LucideIcon> = {
  React: SiReact,
  "Next.js": SiNextdotjs,
  "React Native": SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  "HTML5 / CSS3": SiCss,
  NestJS: SiNestjs,
  "Node.js": SiNodedotjs,
  Symfony: SiSymfony,
  PHP: SiPhp,
  Java: SiOpenjdk,
  "Architecture API REST": Network,
  "API REST": Network,
  "SQL / MySQL": SiMysql,
  SQL: Database,
  Selenium: SiSelenium,
  TestNG: ClipboardCheck,
  JMeter: SiApachejmeter,
  "Tests de charge": Gauge,
  "Tests de régression": History,
  "Recette fonctionnelle": ClipboardCheck,
  n8n: Workflow,
  Python: SiPython,
  "Groq API": Cpu,
  "NLP (BERT, TF-IDF)": Brain,
  SentenceTransformers: Brain,
  "scikit-learn": SiScikitlearn,
  Streamlit: SiStreamlit,
  "Git / GitHub": SiGithub,
  Docker: SiDocker,
  "CI/CD": SiGithubactions,
  "Cybersécurité / DevSecOps": ShieldCheck,
  "Architecture logicielle": Blocks,
  DevOps: Workflow,
  "IA locale": Cpu,
};
